### PR TITLE
chore: first commit with cdk stack for GraphQL API

### PR DESCRIPTION
**Pull request by himabindugit**
Hi @marcelino-sf
Here is my first commit for the code challenge test, please let me know if anyone have any questions, happy to hop on a zoom call for code tour.

Thanks

### CODE REVIEW

**Comment by marcelino-sf** [comment]
Hi @himabindugit, I didn't have the time to review your PR completely, but one of the requirements we had in the readme was to [Write concise and clear commit messages](https://github.com/Superformula/cloud-backend-test#developer-experience). Can you try to do an interactive rebase to separate your work on multiple commits? Then I can continue reviewing your PR.

I really appreciate the time you spent working on this pull request

**Comment by himabindugit** [comment]
Hi @marcelino-sf 
I did see the requirement in readme, just not to overwhelm with so many changes, I made sure all the code is working fine and pushed everything in one go to keep it simple.
Are you asking to push each file separately with the corresponding commit comment about that file? Am I reading your request correctly? Please let me know. I am happy to do that.

**Comment by himabindugit** [comment]
> Hi @marcelino-sf I did see the requirement in readme, just not to overwhelm with so many changes, I made sure all the code is working fine and pushed everything in one go to keep it simple. Are you asking to push each file separately with the corresponding commit comment about that file? Am I reading your request correctly? Please let me know. I am happy to do that.

@marcelino-sf alright assuming you response is Yes, pushing multiple commits with each functionality

**Comment by himabindugit** [comment]
Closing this PR will open new one based on the suggestion here

**Comment by himabindugit** [comment]
I have opened new PR, please ignore first [commit](https://github.com/Superformula/cloud-backend-test/pull/25/commits/2ed0d6ef3c0f7f580e81509c9062544e4186b454) and look into others, thank you

**Comment by himabindugit** [comment]
@marcelino-sf Sorry for the confusion, here is my final [PR](https://github.com/Superformula/cloud-backend-test/pull/26) with valid commits
Thanks

**Pull request closed without merging**
